# Generated by Django 4.1.4 on 2022-12-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="userdb", old_name="userid", new_name="id",),
    ]
